import { Treatment, Testimonial, FaqItem, ClinicStat } from './types';

export const CLINIC_INFO = {
  name: 'Clínica de Podologia Liana Gonçalves',
  shortName: 'Liana Gonçalves',
  legalName: 'Hospital do Pé Ltda',
  tagline: 'Podologia Clínica. Não é Estética, é Saúde.',
  phone: '(67) 3305-0219',
  phoneRaw: '6733050219',
  whatsapp: '(67) 99916-0929',
  whatsappRaw: '5567999160929',
  address: {
    street: 'Rua Doutor Arthur Jorge, 2523',
    neighborhood: 'Monte Castelo',
    city: 'Campo Grande',
    state: 'MS',
    cep: '79010-210',
    reference: 'Próximo à Av. Afonso Pena, com estacionamento na rua',
  },
  hours: 'Segunda a Sexta · 8h às 12h e 13h às 17h',
  rating: 4.9,
  reviewsCount: 207,
  patientsCount: '2.000+',
  successRate: '90%',
  experienceYears: '15 anos',
};

export const CLINIC_STATS: ClinicStat[] = [
  { value: '2.000+', label: 'Pacientes Tratados', sublabel: 'com protocolos clínicos comprovados' },
  { value: '90%', label: 'Taxa de Sucesso', sublabel: 'nos tratamentos especializados' },
  { value: '15 Anos', label: 'De Experiência', sublabel: 'da Podóloga Liana Gonçalves' },
  { value: '207', label: 'Avaliações Google', sublabel: 'média 4.9 estrelas verificadas' },
];

export const PATHOLOGIES_MENU = [
  { id: 'unha-encravada', name: 'Unha encravada', href: '/patologias/unha-encravada', desc: 'Alívio imediato da dor e desobstrução a laser' },
  { id: 'fungos-micose', name: 'Fungos e Micose (Onicomicose)', href: '/patologias/fungos-micose', desc: 'Diagnóstico micológico laboratorial preciso' },
  { id: 'olho-de-peixe', name: 'Olho de peixe (verruga plantar)', href: '/patologias/olho-de-peixe', desc: 'Cauterização e tratamento não traumático' },
  { id: 'pe-diabetico', name: 'Pés do diabético', href: '/patologias/pes-diabetico', desc: 'Semiologia e prevenção de úlceras graves' },
  { id: 'podopediatria', name: 'Podopediatria (Podologia kids)', href: '/patologias/podopediatria', desc: 'Especialista em bebês e crianças' },
  { id: 'podogeriatria', name: 'Podogeriatria', href: '/patologias/podogeriatria', desc: 'Cuidado especializado para a terceira idade' },
  { id: 'calos-calosidades', name: 'Calos e calosidades', href: '/patologias/calos-e-calosidades', desc: 'Desbaste técnico e remoção de núcleos dolorosos' },
  { id: 'podoprofilaxia', name: 'Podoprofilaxia', href: '/patologias/podoprofilaxia', desc: 'Higienização e corte preventivo estéril' },
  { id: 'ozonioterapia', name: 'Ozonioterapia', href: '/ozonioterapia', desc: 'Ozônio medicinal Philozon aprovado CFM 2025' },
];

export const MAIN_CONDITIONS = [
  {
    id: 'fungos',
    title: 'Fungos nas Unhas',
    subtitle: 'Onicomicose Recorrente',
    problem: 'Unhas amareladas, espessas, quebradiças. Vergonha de usar sandálias. Já tentou pomadas e não resolveu?',
    action: 'Diagnóstico com exame micológico laboratorial. Identificamos o fungo exato para o protocolo certo.',
    cta: 'Ver página do tratamento →',
    pageHref: '/patologias/fungos-micose',
    badge: 'Carro-chefe',
    tone: 'peach' as const,
    image: '/images/original/treatment_fungos.webp',
  },
  {
    id: 'unha-encravada',
    title: 'Unha Encravada',
    subtitle: 'Onicocriptose Dolorosa',
    problem: 'Dor intensa a cada passo, inflamação, até pus. Evitando calçados por causa da dor?',
    action: 'Procedimento rápido com analgesia a laser DMC e alívio imediato da dor após retirada da espícula.',
    cta: 'Ver página do tratamento →',
    pageHref: '/patologias/unha-encravada',
    badge: 'Urgência',
    tone: 'sand' as const,
    image: '/images/original/treatment_unha_encravada.webp',
  },
  {
    id: 'pe-diabetico',
    title: 'Pé Diabético',
    subtitle: 'Prevenção & Tratamento',
    problem: 'Feridas que não cicatrizam, dormência, formigamento. O diabético precisa de acompanhamento especializado.',
    action: 'Acompanhamento preventivo com pós-graduação em Diabetes e semiologia detalhada contra úlceras.',
    cta: 'Ver página do tratamento →',
    pageHref: '/patologias/pes-diabetico',
    badge: 'Especialidade',
    tone: 'sage' as const,
    image: '/images/original/treatment_diabetico.webp',
  },
  {
    id: 'calos-calosidades',
    title: 'Calos e Calosidades',
    subtitle: 'Calo com Núcleo & Fissuras',
    problem: 'Dor ao caminhar, fissuras que sangram, pele grossa e endurecida na planta ou calcanhar.',
    action: 'Remoção mecânica precisa de calosidades e extração de núcleos dolorosos com desbaste cirúrgico.',
    cta: 'Ver página do tratamento →',
    pageHref: '/patologias/calos-e-calosidades',
    badge: 'Alívio ao Pisar',
    tone: 'sand' as const,
    image: '/images/original/treatment_calos.jpg',
  },
  {
    id: 'olho-de-peixe',
    title: 'Verruga Plantar',
    subtitle: 'Olho de Peixe (HPV)',
    problem: 'Conhecido como olho de peixe. Dor ao pisar, lesão que cresce e pode se multiplicar se não tratada.',
    action: 'Protocolo clínico com laser e substâncias específicas que eliminam o vírus sem agredir o tecido sadio.',
    cta: 'Ver página do tratamento →',
    pageHref: '/patologias/olho-de-peixe',
    badge: 'Tratamento Preciso',
    tone: 'peach' as const,
    image: '/images/original/treatment_laser.webp',
  },
  {
    id: 'podopediatria',
    title: 'Podopediatria',
    subtitle: 'Podologia Kids & Bebês',
    problem: 'Pés de crianças e bebês precisam de atenção especializada. Somos referência em podologia infantil.',
    action: 'Atendimento afetuoso e lúdico para unhas encravadas de recém-nascidos e correções anatômicas.',
    cta: 'Ver página do tratamento →',
    pageHref: '/patologias/podopediatria',
    badge: 'Referência Kids',
    tone: 'sage' as const,
    image: '/images/original/treatment_podopediatria.png',
  },
];

export const PRICING_TABLE = [
  {
    id: 'price-fungos',
    icon: 'microscope',
    procedure: 'Consulta de Fungos / Onicomicose',
    details: 'Inclui: coleta micológica · análise laboratorial · 1ª limpeza completa · plano de tratamento',
    price: 'R$ 370,00',
    highlight: true,
    tag: 'Carro-chefe',
  },
  {
    id: 'price-urgencia',
    icon: 'activity',
    procedure: 'Consulta para Unha Encravada & Patologias Agudas',
    details: 'O tratamento inclui: procedimento · curativos · laser · retornos. A consulta não é cobrada se feito procedimento no mesmo dia',
    price: 'R$ 150,00*',
    note: '*Valor da consulta não é cobrado se realizar o procedimento no mesmo dia',
    highlight: false,
    tag: 'Urgência',
  },
  {
    id: 'price-podoprofilaxia',
    icon: 'sparkles',
    procedure: 'Podoprofilaxia (Limpeza Completa)',
    details: 'Higienização profunda, corte técnico correto das unhas e cuidados preventivos completos',
    price: 'A partir de R$ 200,00',
    note: 'Valor definido conforme o grau de hidratação e cuidados necessários',
    highlight: false,
    tag: 'Preventivo',
  },
  {
    id: 'price-calos',
    icon: 'footprints',
    procedure: 'Calos, Calosidades e Calo com Núcleo',
    details: 'Remoção especializada com protocolo clínico, desbaste e extração atraumática de núcleo',
    price: 'A partir de R$ 180,00',
    note: 'Investimento conforme número de lesões e profundidade',
    highlight: false,
    tag: 'Alívio Imediato',
  },
  {
    id: 'price-geral',
    icon: 'stethoscope',
    procedure: 'Consulta Geral (demais patologias)',
    details: 'Anamnese completa · exame clínico minucioso · definição do protocolo personalizado. Em todos os atendimentos a consulta não é cobrada caso o tratamento seja contratado no mesmo dia da consulta',
    price: 'R$ 150,00*',
    note: '*Consulta isenta se contratado o tratamento no mesmo dia',
    highlight: false,
    tag: 'Avaliação',
  },
];

export const OZONIOTERAPIA_INFO = {
  badge: 'Aprovado pelo CFM · 2025',
  title: 'Ozonioterapia na mesma clínica',
  description: 'Contamos com a enfermeira Marciana Soares — especialista em ozonioterapia com 15 anos de experiência e equipamento Philozon certificado. 8 técnicas disponíveis para dor crônica, imunidade, fibromialgia, lipedema e muito mais.',
  indications: [
    { icon: 'activity', title: 'Dor Crônica', desc: 'Alívio analgésico e potente efeito anti-inflamatório nas articulações' },
    { icon: 'shield-check', title: 'Imunidade', desc: 'Estímulo e modulação das defesas naturais do organismo' },
    { icon: 'droplets', title: 'Lipedema', desc: 'Descongestão tecidual, drenagem e alívio do peso nas pernas' },
    { icon: 'heart', title: 'Fibromialgia', desc: 'Oxigenação celular profunda e diminuição dos pontos de dor muscular' },
    { icon: 'sparkles', title: 'Fascite Plantar', desc: 'Ação rápida na dor e rigidez ao pisar nos calcanhares' },
    { icon: 'bandage', title: 'Cicatrização de Feridas', desc: 'Acelera a regeneração tecidual em pés diabéticos e úlceras crônicas' },
    { icon: 'microscope', title: 'Ação Antimicrobiana', desc: 'Elimina fungos, bactérias e vírus resistentes sem efeitos colaterais' },
    { icon: 'zap', title: 'Vitalidade Celular', desc: 'Otimização metabólica e aumento da circulação sanguínea periférica' },
  ],
};

export const TREATMENTS: Treatment[] = [
  {
    id: 'fungos-micose',
    name: 'Consulta & Tratamento de Fungos (Onicomicose)',
    category: 'micose',
    badge: 'Protocolo Laboratorial',
    shortDesc: 'Diagnóstico exato através de exame micológico. Sem medicamentos empíricos sem comprovação.',
    fullDesc: 'Identificamos o fungo exato em laboratório credenciado antes de definir o protocolo ideal. O plano inclui desbastamento técnico e higienização terapêutica profunda.',
    includes: [
      'Coleta micológica completa',
      'Análise laboratorial certificada',
      '1ª limpeza e desbastamento completo',
      'Plano de tratamento individualizado',
    ],
    priceFormatted: 'R$ 370,00',
    priceNote: 'Consulta de fungos com análise laboratorial e 1ª sessão inclusas',
    bgTone: 'peach',
    image: '/images/original/treatment_fungos.webp',
  },
  {
    id: 'unha-encravada-urgencia',
    name: 'Unha Encravada com Analgesia a Laser (Urgência)',
    category: 'urgencia',
    badge: 'Alívio Imediato',
    shortDesc: 'Procedimento rápido e seguro para retirada da espícula que causa a dor.',
    fullDesc: 'Atendimento de urgência para alívio imediato da dor. Atendemos casos infeccionados, com granuloma, diabéticos, idosos e bebês.',
    includes: [
      'Analgesia com Laser DMC',
      'Remoção técnica da espícula',
      'Todos os curativos necessários',
      'Todos os retornos de revisão inclusos',
    ],
    priceFormatted: 'R$ 150,00*',
    priceNote: '*Valor da consulta não é cobrado se realizar o procedimento no mesmo dia',
    bgTone: 'sand',
    image: '/images/original/treatment_unha_encravada.webp',
  },
  {
    id: 'pe-diabetico-especializado',
    name: 'Acompanhamento do Pé Diabético',
    category: 'especialidade',
    badge: 'Prevenção Crítica',
    shortDesc: 'Protocolos hospitalares de rastreio de sensibilidade e prevenção de lesões.',
    fullDesc: 'Atendimento conduzido com formação de pós-graduação em Diabetes e Complicações Crônicas. Avaliação de pulsos, sensibilidade tátil e térmica.',
    includes: [
      'Semiologia do pé diabético',
      'Prevenção de úlceras e fissuras',
      'Ozonioterapia medicinal complementar',
      'Corte preventivo e hidratação profunda',
    ],
    priceFormatted: 'R$ 150,00*',
    priceNote: '*Consulta isenta ao iniciar o tratamento terapêutico no dia',
    bgTone: 'sage',
    image: '/images/original/treatment_diabetico.webp',
  },
  {
    id: 'podoprofilaxia',
    name: 'Podoprofilaxia Clínica (Limpeza Profunda)',
    category: 'preventivo',
    badge: 'Saúde Contínua',
    shortDesc: 'Limpeza minuciosa com assepsia hospitalar para prevenção ativa de patologias.',
    fullDesc: 'Muito além de um cuidado estético: corte técnico anatômico correto que impede encravamentos, remoção de hiperqueratose e higienização com autoclave.',
    includes: [
      'Higienização antisséptica estéril',
      'Corte técnico correto das lâminas',
      'Desbaste de calosidades superficiais',
      'Hidratação terapêutica profunda',
    ],
    priceFormatted: 'A partir de R$ 200,00',
    priceNote: 'Valor personalizado conforme o grau de hidratação e cuidados necessários',
    bgTone: 'sage',
    image: '/images/original/clinic_room_1.webp',
  },
  {
    id: 'calos-calosidades',
    name: 'Remoção de Calos e Calo com Núcleo',
    category: 'urgencia',
    badge: 'Eliminação da Pressão',
    shortDesc: 'Remoção indolor do núcleo córneo que provoca dores agudas ao pisar.',
    fullDesc: 'Trabalho mecânico com instrumental cirúrgico estéril e identificação da causa biomecânica do atrito, prevenindo a reincidência.',
    includes: [
      'Identificação da causa do atrito',
      'Desbastamento com lâminas descartáveis',
      'Remoção atraumática do núcleo',
      'Orientações posturais e de calçados',
    ],
    priceFormatted: 'A partir de R$ 180,00',
    priceNote: 'Investimento conforme número de lesões e profundidade',
    bgTone: 'peach',
    image: '/images/original/treatment_calos.jpg',
  },
  {
    id: 'podopediatria',
    name: 'Podopediatria (Podologia para Bebês e Crianças)',
    category: 'especialidade',
    badge: 'Referência em MS',
    shortDesc: 'Cuidado afetuoso e técnico para recém-nascidos e crianças em fase de crescimento.',
    fullDesc: 'Referência em Campo Grande para tratar unhas encravadas congênitas ou adquiridas em bebês, marcha atípica e verrugas infantis com máxima delicadeza.',
    includes: [
      'Ambiente lúdico e acolhedor',
      'Técnicas 100% não traumáticas',
      'Orientações aos pais sobre calçados',
      'Acompanhamento do desenvolvimento ungueal',
    ],
    priceFormatted: 'R$ 150,00*',
    priceNote: '*Consulta isenta se o procedimento for realizado no mesmo dia',
    bgTone: 'sand',
    image: '/images/original/treatment_podopediatria.png',
  },
  {
    id: 'ozonioterapia-clinica',
    name: 'Ozonioterapia Medicinal',
    category: 'especialidade',
    badge: 'Enfª Marciana Soares',
    shortDesc: 'Aplicação de ozônio medicinal para acelerar cicatrização, analgesia e ação antimicrobiana.',
    fullDesc: 'Parceria clínica com a enfermeira Marciana Soares, especialista com 15 anos de atuação. Equipamento Philozon certificado pelo CFM para tratamento de dor crônica e lesões.',
    includes: [
      'Ação fungicida e bactericida potente',
      'Estímulo à oxigenação tecidual',
      'Tratamento de dor crônica e fascite plantar',
      'Equipamento Philozon homologado',
    ],
    priceFormatted: 'Consulte Sessão',
    priceNote: 'Planos individuais ou pacotes de sessões conforme recomendação',
    bgTone: 'sage',
    image: '/images/original/treatment_ozonioterapia.png',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'rev-1',
    name: 'Sandra Luzinete Felix de Freitas',
    date: '12/02/2026',
    rating: 5,
    text: 'Liana é uma ótima profissional. Gostei bastante do atendimento na clínica, tudo muito limpo e organizado. Super indico!',
    verifiedSource: 'Avaliação Verificada no Google',
  },
  {
    id: 'rev-2',
    name: 'Mirian Marconi',
    date: '10/02/2026',
    rating: 5,
    text: 'Excelente atendimento. Profissional Liana experiente, educada e é muito simpática. O alívio da dor foi na hora.',
    verifiedSource: 'Avaliação Verificada no Google',
  },
  {
    id: 'rev-3',
    name: 'Roseli Gomes',
    date: '09/02/2026',
    rating: 5,
    text: 'Foi um alívio imenso, graças a Deus. Estava há semanas com dor e a Liana resolveu com muita delicadeza.',
    verifiedSource: 'Avaliação Verificada no Google',
  },
  {
    id: 'rev-4',
    name: 'Jane Coutinho',
    date: '06/02/2026',
    rating: 5,
    text: 'Trabalho maravilhoso! Super recomendo! Atendimento impecável desde a recepção até o procedimento.',
    verifiedSource: 'Avaliação Verificada no Google',
  },
  {
    id: 'rev-5',
    name: 'Cristina Treu',
    date: '22/01/2026',
    rating: 5,
    text: 'O atendimento foi para a minha mãe, que é idosa e foi excelente desde a recepção. A clínica é confortável, espaçosa e tem muita acessibilidade. Quanto à podologista Liana, só tenho elogios, muito atenciosa, paciente e cuidadosa com todos os detalhes. Estão todos de parabéns!!',
    verifiedSource: 'Avaliação Verificada no Google',
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    id: 'faq-1',
    question: 'O procedimento vai doer?',
    answer: 'Usamos analgesia com laser DMC de última geração e anestésico tópico antes de qualquer procedimento invasivo. Na unha encravada, por exemplo, o procedimento é extremamente rápido e o alívio da dor é imediato após a retirada da espícula. A grande maioria dos nossos pacientes relata surpresa positiva por não sentir o desconforto que temiam.',
  },
  {
    id: 'faq-2',
    question: 'Quanto custa a consulta?',
    answer: 'A consulta padrão custa R$ 150 e inclui anamnese completa, exame da patologia e definição do protocolo personalizado. O valor da consulta não é cobrado se o tratamento for iniciado no mesmo dia. Para fungos/micose, a consulta é R$ 370 e já inclui coleta para exame micológico laboratorial, primeira limpeza completa e plano de tratamento estruturado.',
  },
  {
    id: 'faq-3',
    question: 'Vocês atendem plano de saúde?',
    answer: 'Atendemos exclusivamente na modalidade particular. Isso nos permite manter protocolos médicos rigorosos, instrumental estéril de uso único ou autoclavado e tempo de consulta sem pressa. Fornecemos recibo formal para que você possa solicitar reembolso junto ao seu convênio. Aceitamos Pix, débito, dinheiro e parcelamos em até 10x no cartão de crédito.',
  },
  {
    id: 'faq-4',
    question: 'Posso enviar uma foto pelo WhatsApp para saber o valor?',
    answer: 'Não precificamos procedimentos apenas por foto, e fazemos isso pela sua segurança e precisão médica. O valor correto e o protocolo adequado só podem ser determinados ao avaliar pessoalmente a profundidade da lesão, integridade tecidual, vascularização e comorbidades (como diabetes). Isso garante que você receba o tratamento exato, sem custos surpresa.',
  },
  {
    id: 'faq-5',
    question: 'Pessoas com diabetes podem ser atendidas com segurança?',
    answer: 'Sim, e é fundamental que o paciente diabético tenha acompanhamento podológico regular! Liana Gonçalves possui pós-graduação em Diabetes e Complicações Crônicas e especialização em Semiologia do Pé Diabético. Todo o procedimento é executado com técnicas atraumáticas e monitoramento preventivo contra úlceras.',
  },
  {
    id: 'faq-6',
    question: 'Vocês atendem bebês e crianças (Podopediatria)?',
    answer: 'Sim! Somos referência em Podopediatria em Campo Grande. Atendemos recém-nascidos e bebês com unhas encravadas congênitas com carinho redobrado, instrumental infantil adaptado e sem trauma para os pequenos e para os pais.',
  },
];
